Repository CubicMC/cubic-server, pull requests merged in 2022-09, with the labels that each got.

#4 GTest
  CMakeLists.txt
  hello_test.cc
  math/CMakeLists.txt
  math/Math.cpp
  math/Math.hpp
  math/Math_unittest.cpp
Labels: documentation, enhancement

#3 Add basic network stuff
  .gitignore
  CMakeLists.txt
  cubic-server/CMakeLists.txt
  cubic-server/Client.cpp
  cubic-server/Client.hpp
  cubic-server/Server.cpp
  cubic-server/Server.hpp
  cubic-server/main.cpp
Labels: enhancement

#7 Add a proper README to the project
  README.md
Labels: enhancement

#10 Use std::min instead of a ternary in Client::_sendData
  cubic-server/Client.cpp
Labels: enhancement

#12 Use self-hosted CI runners
  .github/workflows/cmake.yml
Labels: enhancement

#13 Change compilator for the CI
  .github/workflows/cmake.yml
Labels: bug

#11 Packet parsing simplification + packet creation
  CMakeLists.txt
  cubic-server/main.cpp
  protocol/CMakeLists.txt
  protocol/ClientPackets.cpp
  protocol/ClientPackets.hpp
  protocol/Packet.cpp
  protocol/Packet.hpp
  protocol/PacketUtils.hpp
  protocol/ParseExceptions.hpp
  protocol/ServerPackets.cpp
  protocol/ServerPackets.hpp
  protocol/typeSerialization.hpp
Labels: enhancement

#19 Packet callback system
  .gitignore
  cubic-server/Client.cpp
  cubic-server/Client.hpp
  cubic-server/Server.cpp
  cubic-server/Server.hpp
  cubic-server/main.cpp
  protocol/PacketUtils.hpp
  protocol/ServerPackets.hpp
  protocol/typeSerialization.hpp
Labels: enhancement

#16 Logs
  CMakeLists.txt
  cubic-server/CMakeLists.txt
  logging/CMakeLists.txt
  logging/FileAndFolderHandler.cpp
  logging/FileAndFolderHandler.hpp
  logging/FileAndFolderHandler_unittest.cpp
  logging/Logger.cpp
  logging/Logger.hpp
  logging/Logger_unittest.cpp
  logging/TimeFormatter.cpp
  logging/TimeFormatter.hpp
  logging/TimeFormatter_unittest.cpp
Labels: enhancement

#17 Gtk - opening a window
  CMakeLists.txt
  interface/CMakeLists.txt
  interface/ManagementInterface.cpp
  interface/ManagementInterface.hpp
  interface/main.cpp
Labels: enhancement

#15 Add Configuration - Handling the config.yml
  CMakeLists.txt
  configuration/CMakeLists.txt
  configuration/ConfigHandler.cpp
  configuration/ConfigHandler.hpp
  configuration/ConfigHandler_unittest.cpp
  configuration/config.yml
Labels: enhancement

#30 Refactor to use a Singleton
  logging/Logger.cpp
  logging/Logger.hpp
  logging/Logger_unittest.cpp
Labels: enhancement
