Repository CubicMC/cubic-server, pull requests merged in 2023-05, with the labels that each got.

#142 Add SpawnEntity packet
  cubic-server/Player.cpp
  cubic-server/Player.hpp
  cubic-server/protocol/ClientPackets.cpp
  cubic-server/protocol/ClientPackets.hpp
Labels: enhancement

#146 correcting segfault on musl libc (void linux)
  cubic-server/Server.cpp
Labels: bug

#155 Compiling on clang done.
  .github/workflows/auto_build.yml
  .github/workflows/auto_tests.yml
  .github/workflows/requested_build.yml
  .github/workflows/requested_tests.yml
  CMakeLists.txt
  cubic-server/Dimension.hpp
  cubic-server/World.hpp
  cubic-server/chat/ChatMessageUtils.hpp
  cubic-server/chat/Message.hpp
  cubic-server/chat/SimpleMessage.cpp
  cubic-server/chat/SimpleMessage.hpp
  cubic-server/chat/events/Click.hpp
  cubic-server/chat/events/Hover.hpp
  cubic-server/chat/events/clicks/ChangePage.hpp
  cubic-server/chat/events/clicks/CopyToClipboard.hpp
  cubic-server/chat/events/clicks/OpenUrl.hpp
  cubic-server/chat/events/clicks/RunCommand.hpp
  cubic-server/chat/events/clicks/SuggestCommand.hpp
  cubic-server/chat/events/hovers/Entity.hpp
  cubic-server/chat/events/hovers/Item.hpp
  cubic-server/chat/events/hovers/Text.hpp
  cubic-server/command_parser/commands/CommandBase.hpp
  cubic-server/command_parser/commands/Deop.hpp
  cubic-server/command_parser/commands/DumpChunk.hpp
  cubic-server/command_parser/commands/Help.hpp
  cubic-server/command_parser/commands/Log.hpp
  cubic-server/command_parser/commands/Op.hpp
  cubic-server/command_parser/commands/QuestionMark.hpp
  cubic-server/command_parser/commands/Reload.hpp
  cubic-server/command_parser/commands/Seed.hpp
  cubic-server/command_parser/commands/Stop.hpp
  cubic-server/command_parser/commands/Time.hpp
  cubic-server/concept.hpp
  cubic-server/configuration/ArgumentHolder.hpp
  cubic-server/default/DefaultWorld.hpp
  cubic-server/default/DefaultWorldGroup.hpp
  cubic-server/default/Overworld.hpp
  cubic-server/default/TheEnd.hpp
  cubic-server/default/TheNether.hpp
  cubic-server/generation/generator.cpp
Labels: bug, External

#134 devcontainer improvment
  .devcontainer/Dockerfile
Labels: enhancement

#153 Recipe system, does not handle item tags
  cubic-server/CMakeLists.txt
  cubic-server/Server.cpp
  cubic-server/Server.hpp
  cubic-server/recipes/Blasting.cpp
  cubic-server/recipes/Blasting.hpp
  cubic-server/recipes/CMakeLists.txt
  cubic-server/recipes/CampfireCooking.cpp
  cubic-server/recipes/CampfireCooking.hpp
  cubic-server/recipes/CraftingShaped.cpp
  cubic-server/recipes/CraftingShaped.hpp
  cubic-server/recipes/CraftingShapeless.cpp
  cubic-server/recipes/CraftingShapeless.hpp
  cubic-server/recipes/Recipes.cpp
  cubic-server/recipes/Recipes.hpp
  cubic-server/recipes/Smelting.cpp
  cubic-server/recipes/Smelting.hpp
  cubic-server/recipes/Smithing.cpp
  cubic-server/recipes/Smithing.hpp
  cubic-server/recipes/Smoking.cpp
  cubic-server/recipes/Smoking.hpp
  cubic-server/recipes/StoneCutting.cpp
  cubic-server/recipes/StoneCutting.hpp
Labels: feature

#147 World storage update
  .gitignore
  CMakeLists.txt
  cubic-server/Chat.cpp
  cubic-server/Client.cpp
  cubic-server/Client.hpp
  cubic-server/CommandLine.cpp
  cubic-server/Dimension.cpp
  cubic-server/Dimension.hpp
  cubic-server/Player.cpp
  cubic-server/Player.hpp
  cubic-server/Server.cpp
  cubic-server/chat/CMakeLists.txt
  cubic-server/chat/Message.cpp
  cubic-server/chat/Message.hpp
  cubic-server/chat/events/hovers/Text.cpp
  cubic-server/chat/events/hovers/Text.hpp
  cubic-server/chat/translationFromKey.cpp
  cubic-server/command_parser/commands/DumpChunk.cpp
  cubic-server/command_parser/commands/Seed.cpp
  cubic-server/concept.hpp
  cubic-server/configuration/ArgumentsParser.hpp
  cubic-server/default/Overworld.cpp
  cubic-server/generation/generator.cpp
  cubic-server/generation/overworld.hpp
  cubic-server/logging/Logger.cpp
  cubic-server/logging/Logger.hpp
  cubic-server/nbt.hpp
  cubic-server/options.hpp
  cubic-server/protocol/ClientPackets.cpp
  cubic-server/protocol/ClientPackets.hpp
  cubic-server/protocol/PacketUtils.hpp
  cubic-server/protocol/common.hpp
  cubic-server/protocol/serialization/add.hpp
  cubic-server/protocol/serialization/addPrimaryType.hpp
  cubic-server/types.cpp
  cubic-server/types.hpp
  cubic-server/world_storage/CMakeLists.txt
  cubic-server/world_storage/ChunkColumn.cpp
  cubic-server/world_storage/ChunkColumn.hpp
  cubic-server/world_storage/DynamicStorage.hpp
  cubic-server/world_storage/Level.cpp
  cubic-server/world_storage/Level.hpp
  cubic-server/world_storage/Palette.cpp
  cubic-server/world_storage/Palette.hpp
  cubic-server/world_storage/Section.cpp
  cubic-server/world_storage/Section.hpp
  cubic-server/world_storage/tests/DynamicStorage_test.cpp
  cxx_flag_overrides.cmake
Labels: enhancement, URGENT

#159 Special recipes handling to import every recipe and prevent exceptions
  cubic-server/recipes/Blasting.cpp
  cubic-server/recipes/Blasting.hpp
  cubic-server/recipes/CMakeLists.txt
  cubic-server/recipes/CampfireCooking.cpp
  cubic-server/recipes/CampfireCooking.hpp
  cubic-server/recipes/CraftingShaped.cpp
  cubic-server/recipes/CraftingShaped.hpp
  cubic-server/recipes/CraftingShapeless.cpp
  cubic-server/recipes/CraftingShapeless.hpp
  cubic-server/recipes/Recipes.cpp
  cubic-server/recipes/Recipes.hpp
  cubic-server/recipes/Smelting.cpp
  cubic-server/recipes/Smelting.hpp
  cubic-server/recipes/Smithing.cpp
  cubic-server/recipes/Smithing.hpp
  cubic-server/recipes/Smoking.cpp
  cubic-server/recipes/Smoking.hpp
  cubic-server/recipes/SpecialArmorDye.cpp
  cubic-server/recipes/SpecialArmorDye.hpp
  cubic-server/recipes/SpecialBannerDuplicate.cpp
  cubic-server/recipes/SpecialBannerDuplicate.hpp
  cubic-server/recipes/SpecialBookCloning.cpp
  cubic-server/recipes/SpecialBookCloning.hpp
  cubic-server/recipes/SpecialFireworkRocket.cpp
  cubic-server/recipes/SpecialFireworkRocket.hpp
  cubic-server/recipes/SpecialFireworkStar.cpp
  cubic-server/recipes/SpecialFireworkStar.hpp
  cubic-server/recipes/SpecialFireworkStarFade.cpp
  cubic-server/recipes/SpecialFireworkStarFade.hpp
  cubic-server/recipes/SpecialMapCloning.cpp
  cubic-server/recipes/SpecialMapCloning.hpp
  cubic-server/recipes/SpecialMapExtending.cpp
  cubic-server/recipes/SpecialMapExtending.hpp
  cubic-server/recipes/SpecialRepairItem.cpp
  cubic-server/recipes/SpecialRepairItem.hpp
  cubic-server/recipes/SpecialShieldDecoration.cpp
  cubic-server/recipes/SpecialShieldDecoration.hpp
  cubic-server/recipes/SpecialShulkerboxColoring.cpp
  cubic-server/recipes/SpecialShulkerboxColoring.hpp
  cubic-server/recipes/SpecialSuspiciousStew.cpp
  cubic-server/recipes/SpecialSuspiciousStew.hpp
  cubic-server/recipes/SpecialTippedArrow.cpp
  cubic-server/recipes/SpecialTippedArrow.hpp
  cubic-server/recipes/StoneCutting.cpp
  cubic-server/recipes/StoneCutting.hpp
Labels: bug, URGENT

#157 Add Jenkins CI
  .github/workflows/auto_build.yml
  .github/workflows/auto_tests.yml
  .github/workflows/publish.yml
  .github/workflows/requested_build.yml
  .github/workflows/requested_tests.yml
  CMakeLists.txt
  Jenkinsfile
  blocks.cmake
  configuration/config.yml
  cubic-server/Client.cpp
  cubic-server/CommandLine.cpp
  cubic-server/Server.cpp
  cubic-server/interface/LogsInterface.cpp
Labels: enhancement

#163 Fix added boost fetch to CMake
  CMakeLists.txt
Labels: bug

#168 Online mode
  CMakeLists.txt
  cubic-server/CMakeLists.txt
  cubic-server/Checksum.cpp
  cubic-server/Checksum.hpp
  cubic-server/Client.cpp
  cubic-server/Client.hpp
  cubic-server/Dimension.cpp
  cubic-server/EASEncryptionHandler.cpp
  cubic-server/EASEncryptionHandler.hpp
  cubic-server/Player.cpp
  cubic-server/Player.hpp
  cubic-server/RSAEncryptionHandler.cpp
  cubic-server/RSAEncryptionHandler.hpp
  cubic-server/Server.cpp
  cubic-server/Server.hpp
  cubic-server/World.cpp
  cubic-server/main.cpp
  cubic-server/protocol/ClientPackets.cpp
  cubic-server/protocol/ClientPackets.hpp
  cubic-server/protocol/ServerPackets.cpp
  cubic-server/protocol/ServerPackets.hpp
  cubic-server/protocol/common.hpp
  cubic-server/types.cpp
  cubic-server/types.hpp
Labels: enhancement

#140 Add basic architechture of tree generation
  cubic-server/Client.cpp
  cubic-server/Dimension.cpp
  cubic-server/Dimension.hpp
  cubic-server/Player.cpp
  cubic-server/World.cpp
  cubic-server/World.hpp
  cubic-server/default/DefaultWorld.cpp
  cubic-server/default/DefaultWorld.hpp
  cubic-server/default/DefaultWorldGroup.cpp
  cubic-server/default/Overworld.cpp
  cubic-server/default/Overworld.hpp
  cubic-server/default/TheEnd.hpp
  cubic-server/default/TheNether.hpp
  cubic-server/generation/CMakeLists.txt
  cubic-server/generation/features/CMakeLists.txt
  cubic-server/generation/features/tree/CMakeLists.txt
  cubic-server/generation/features/tree/oak.cpp
  cubic-server/generation/features/tree/oak.hpp
  cubic-server/generation/features/tree/tree.hpp
  cubic-server/generation/generator.cpp
  cubic-server/generation/generator.hpp
  cubic-server/generation/overworld.cpp
  cubic-server/generation/overworld.hpp
  cubic-server/main.cpp
  cubic-server/world_storage/ChunkColumn.cpp
  cubic-server/world_storage/ChunkColumn.hpp
  cubic-server/world_storage/Level.cpp
  cubic-server/world_storage/Level.hpp
  cubic-server/world_storage/Persistence.cpp
Labels: enhancement, feature

#143 Plugin Manager
  CMakeLists.txt
  cubic-server/CMakeLists.txt
  cubic-server/LivingEntity.cpp
  cubic-server/Player.cpp
  cubic-server/PluginInterface.hpp
  cubic-server/PluginManager.cpp
  cubic-server/PluginManager.hpp
  cubic-server/Server.cpp
  cubic-server/Server.hpp
  cubic-server/World.cpp
  cubic-server/events/CMakeLists.txt
  cubic-server/events/CancelEvents.cpp
  cubic-server/events/CancelEvents.hpp
  cubic-server/events/Events.hpp
Labels: feature
