Repository CubicMC/cubic-server, pull requests merged in 2023-11, with the labels that each got.

#235 Prometheus data exporting
  CMakeLists.txt
  cubic-server/CMakeLists.txt
  cubic-server/Client.cpp
  cubic-server/Player.cpp
  cubic-server/PrometheusExporter.cpp
  cubic-server/PrometheusExporter.hpp
  cubic-server/Server.cpp
  cubic-server/Server.hpp
  cubic-server/default/Overworld.cpp
  cubic-server/default/Overworld.hpp
  cubic-server/default/TheEnd.cpp
  cubic-server/default/TheEnd.hpp
  cubic-server/default/TheNether.cpp
  cubic-server/default/TheNether.hpp
  cubic-server/main.cpp
  cubic-server/protocol/metadata.hpp
Labels: feature

#238 Put back encryption to default to true
  cubic-server/main.cpp
Labels: bug

#239 Fix race conditions in chunk sending after gen
  cubic-server/Dimension.cpp
  cubic-server/Player.cpp
Labels: bug

#229 Ore patches generation
  .devcontainer/Dockerfile
  cubic-server/generation/features/CMakeLists.txt
  cubic-server/generation/features/underground/CMakeLists.txt
  cubic-server/generation/features/underground/OreVein.cpp
  cubic-server/generation/features/underground/OreVein.hpp
  cubic-server/world_storage/ChunkColumn.cpp
Labels: feature

#245 Fix nbt being forgor when dropping an item
  cubic-server/Player.cpp
  cubic-server/entities/Entity.cpp
  cubic-server/logging/formating.hpp
  cubic-server/logging/logging.hpp
  cubic-server/protocol/Structures.hpp
  cubic-server/protocol/container/Container.cpp
Labels: bug

#242 Fix ore generation
  cubic-server/generation/features/underground/OreVein.cpp
  cubic-server/world_storage/ChunkColumn.cpp
Labels: bug, enhancement

#237 Tps command
  cubic-server/Dimension.cpp
  cubic-server/Dimension.hpp
  cubic-server/PrometheusExporter.cpp
  cubic-server/PrometheusExporter.hpp
  cubic-server/Server.cpp
  cubic-server/World.cpp
  cubic-server/World.hpp
  cubic-server/allCommands.hpp
  cubic-server/command_parser/commands/CMakeLists.txt
  cubic-server/command_parser/commands/MSPT.cpp
  cubic-server/command_parser/commands/MSPT.hpp
  cubic-server/command_parser/commands/Tps.cpp
  cubic-server/command_parser/commands/Tps.hpp
  cubic-server/command_parser/selectors/selectors.cpp
  cubic-server/generation/features/tree/pine.cpp
  cubic-server/generation/features/tree/spruce.cpp
  cubic-server/types.cpp
  cubic-server/types.hpp
  cubic-server/world_storage/ChunkColumn.hpp
Labels: feature

#248 Jenkins caching
  Jenkinsfile
Labels: enhancement

#250 211 instant break blocks do not drop anything
  blocks.cmake
  cubic-server/Player.cpp
  cubic-server/Server.cpp
  cubic-server/Server.hpp
  cubic-server/command_parser/commands/DumpChunk.cpp
  cubic-server/protocol_id_converter/CMakeLists.txt
  cubic-server/protocol_id_converter/blockDataConverter.cpp
  cubic-server/protocol_id_converter/blockDataConverter.hpp
  cubic-server/protocol_id_converter/blockIdConverter.cpp
  cubic-server/protocol_id_converter/blockIdConverter.hpp
  cubic-server/world_storage/ChunkColumn.cpp
Labels: bug, enhancement

#223 Item durability handling
  cubic-server/Player.cpp
  cubic-server/items/UsableItem.hpp
  cubic-server/protocol/CMakeLists.txt
  cubic-server/protocol/Structures.cpp
  cubic-server/protocol/Structures.hpp
Labels: feature
