Repository CubicMC/cubic-server, pull requests merged in 2023-09, with the labels that each got.

#202 Add Doxygen doc generation
  cubic-server/Chat.hpp
  cubic-server/Dimension.hpp
  docs/.gitignore
  docs/Doxyfile
  docs/ci.sh
  docs/logo.png
Labels: documentation

#203 Entity metadata support
  cubic-server/Dimension.cpp
  cubic-server/Dimension.hpp
  cubic-server/Entity.cpp
  cubic-server/Entity.hpp
  cubic-server/Item.cpp
  cubic-server/Item.hpp
  cubic-server/LivingEntity.cpp
  cubic-server/LivingEntity.hpp
  cubic-server/Player.cpp
  cubic-server/Player.hpp
  cubic-server/RSAEncryptionHandler.cpp
  cubic-server/command_parser/commands/Teleport.cpp
  cubic-server/logging/formating.hpp
  cubic-server/math/Vector3.hpp
  cubic-server/protocol/CMakeLists.txt
  cubic-server/protocol/ClientPackets.cpp
  cubic-server/protocol/ClientPackets.hpp
  cubic-server/protocol/metadata.cpp
  cubic-server/protocol/metadata.hpp
  cubic-server/types.hpp
  docs/Doxyfile
Labels: enhancement

#206 Fix proposal for sound events
  cubic-server/Player.cpp
  cubic-server/Player.hpp
  cubic-server/Server.cpp
  cubic-server/Server.hpp
  cubic-server/SoundSystem.cpp
  cubic-server/protocol/ClientPackets.cpp
  cubic-server/protocol/ClientPackets.hpp
  cubic-server/protocol_id_converter/CMakeLists.txt
  cubic-server/protocol_id_converter/blockStates.cpp
  cubic-server/protocol_id_converter/blockStates.hpp
  cubic-server/protocol_id_converter/itemConverter.cpp
  cubic-server/protocol_id_converter/itemConverter.hpp
  cubic-server/protocol_id_converter/soundEventConverter.cpp
  cubic-server/protocol_id_converter/soundEventConverter.hpp
  cubic-server/types.hpp
Labels: bug

#204 Add seed-based randomized Bedrock generation
  cubic-server/generation/generator.cpp
  cubic-server/generation/generator.hpp
  cubic-server/world_storage/ChunkColumn.cpp
Labels: enhancement

#200 Add the feature "Forest Rock"
  cubic-server/generation/features/CMakeLists.txt
  cubic-server/generation/features/surface/CMakeLists.txt
  cubic-server/generation/features/surface/forestRock.cpp
  cubic-server/generation/features/surface/forestRock.hpp
  cubic-server/generation/features/tree/birch.cpp
  cubic-server/generation/features/tree/birch.hpp
  cubic-server/generation/features/tree/jungle.cpp
  cubic-server/generation/features/tree/jungle.hpp
  cubic-server/generation/features/tree/oak.cpp
  cubic-server/generation/features/tree/oak.hpp
  cubic-server/generation/features/tree/pine.cpp
  cubic-server/generation/features/tree/pine.hpp
  cubic-server/generation/features/tree/spruce.cpp
  cubic-server/generation/features/tree/spruce.hpp
  cubic-server/generation/features/tree/tree.cpp
  cubic-server/generation/features/tree/tree.hpp
  cubic-server/generation/generator.cpp
  cubic-server/generation/generator.hpp
  cubic-server/world_storage/ChunkColumn.cpp
Labels: feature

#209 Foliage distance generation
  cubic-server/generation/features/tree/pine.cpp
  cubic-server/generation/features/tree/spruce.cpp
  cubic-server/generation/features/tree/tree.cpp
  cubic-server/generation/features/tree/tree.hpp
  cubic-server/math/CMakeLists.txt
  cubic-server/math/Vector3.cpp
  cubic-server/math/Vector3.hpp
  cubic-server/types.cpp
  cubic-server/types.hpp
Labels: enhancement

#205 Net compression
  cubic-server/CMakeLists.txt
  cubic-server/Client.cpp
  cubic-server/Client.hpp
  cubic-server/CompressionUtils.cpp
  cubic-server/CompressionUtils.hpp
  cubic-server/Server.cpp
  cubic-server/Server.hpp
  cubic-server/main.cpp
  cubic-server/protocol/ClientPackets.cpp
  cubic-server/protocol/ClientPackets.hpp
Labels: enhancement
