Repository CubicMC/cubic-server, pull requests merged in 2023-07, with the labels that each got.

#177 Registry
  CMakeLists.txt
  cubic-server/CMakeLists.txt
  cubic-server/Client.cpp
  cubic-server/Dimension.cpp
  cubic-server/Server.cpp
  cubic-server/Server.hpp
  cubic-server/chat/CMakeLists.txt
  cubic-server/events/CancelEvents.cpp
  cubic-server/nbt.hpp
  cubic-server/protocol/ClientPackets.hpp
  cubic-server/protocol/common.hpp
  cubic-server/registry/Biome.cpp
  cubic-server/registry/Biome.hpp
  cubic-server/registry/CMakeLists.txt
  cubic-server/registry/Chat.cpp
  cubic-server/registry/Chat.hpp
  cubic-server/registry/Dimension.cpp
  cubic-server/registry/Dimension.hpp
  cubic-server/registry/MasterRegistry.cpp
  cubic-server/registry/MasterRegistry.hpp
  cubic-server/registry/Registry.cpp
  cubic-server/registry/Registry.hpp
  cubic-server/types.cpp
  cubic-server/types.hpp
Labels: enhancement

#181 Add Jungle tree generation
  cubic-server/generation/features/tree/CMakeLists.txt
  cubic-server/generation/features/tree/jungle.cpp
  cubic-server/generation/features/tree/jungle.hpp
  cubic-server/generation/features/tree/tree.hpp
Labels: feature

#182 Add Birch tree generation
  cubic-server/generation/features/tree/CMakeLists.txt
  cubic-server/generation/features/tree/birch.cpp
  cubic-server/generation/features/tree/birch.hpp
Labels: feature

#183 Added a way to insert item/slot into a container
  cubic-server/protocol/container/Container.cpp
  cubic-server/protocol/container/Container.hpp
  cubic-server/protocol/container/Inventory.cpp
  cubic-server/protocol/container/Inventory.hpp
Labels: enhancement

#190 Make shallow clones for deps
  CMakeLists.txt
Labels: enhancement

#191 Fix player synchronization, finally
  cubic-server/Entity.cpp
  cubic-server/Player.cpp
  cubic-server/Player.hpp
Labels: bug
