Repository CubicMC/cubic-server, pull requests merged in 2023-12, with the labels that each got.

#251 Add "flint and steel" item handling
  .gitignore
  cubic-server/Player.cpp
  cubic-server/items/CMakeLists.txt
  cubic-server/items/UsableItem.hpp
  cubic-server/items/usable-items/CMakeLists.txt
  cubic-server/items/usable-items/FlintAndSteel.cpp
  cubic-server/items/usable-items/FlintAndSteel.hpp
  cubic-server/protocol/Structures.cpp
  cubic-server/protocol/Structures.hpp
  cubic-server/world_storage/ChunkColumn.cpp
  cubic-server/world_storage/ChunkColumn.hpp
  generators/protocol_block_ids.py
Labels: enhancement, feature

#253 Add tool and weapon damage
  cubic-server/Player.cpp
  cubic-server/Player.hpp
  cubic-server/entities/LivingEntity.cpp
  cubic-server/entities/LivingEntity.hpp
  cubic-server/items/CMakeLists.txt
  cubic-server/items/toolsDamage.hpp
Labels: enhancement, feature

#254 Add hoe
  cubic-server/Player.cpp
  cubic-server/items/UsableItem.hpp
  cubic-server/items/usable-items/CMakeLists.txt
  cubic-server/items/usable-items/FlintAndSteel.cpp
  cubic-server/items/usable-items/FlintAndSteel.hpp
  cubic-server/items/usable-items/Hoe.cpp
  cubic-server/items/usable-items/Hoe.hpp
  cubic-server/protocol/Structures.cpp
  cubic-server/protocol/Structures.hpp
Labels: feature

#255 Plains biome generation fix
  cubic-server/Player.cpp
  cubic-server/generation/features/surface/CMakeLists.txt
  cubic-server/generation/features/surface/Vegetation.cpp
  cubic-server/generation/features/surface/Vegetation.hpp
  cubic-server/generation/features/tree/oak.cpp
  cubic-server/generation/generator.cpp
  cubic-server/generation/generator.hpp
  cubic-server/generation/overworld.cpp
  cubic-server/registry/Biome.hpp
  cubic-server/world_storage/ChunkColumn.cpp
Labels: enhancement

#259 Plains documentation
  cubic-server/generation/features/surface/Vegetation.cpp
  cubic-server/generation/overworld.cpp
Labels: documentation
