Repository CubicMC/cubic-server, pull requests merged in 2023-01, with the labels that each got.

#71 Fix logs update (commented for some reason)
  cubic-server/interface/LogsInterface.cpp
Labels: bug

#70 Make compilation on FreeBSD work
  CMakeLists.txt
  cubic-server/Client.hpp
  cubic-server/Server.hpp
  cubic-server/interface/LogsInterface.cpp
  cubic-server/interface/ManagementInterface.cpp
  cubic-server/interface/PlayersInterface.cpp
Labels: bug

#72 Add argument parsing
  CMakeLists.txt
  cubic-server/main.cpp
Labels: enhancement

#42 World Data Structures
  cubic-server/CMakeLists.txt
  cubic-server/Dimension.cpp
  cubic-server/Dimension.hpp
  cubic-server/World.cpp
  cubic-server/World.hpp
  cubic-server/world_storage/CMakeLists.txt
  cubic-server/world_storage/ChunkColumn.cpp
  cubic-server/world_storage/ChunkColumn.hpp
  cubic-server/world_storage/Level.cpp
  cubic-server/world_storage/Level.hpp
  cubic-server/world_storage/LevelData.cpp
  cubic-server/world_storage/LevelData.hpp
  cubic-server/world_storage/tests/ChunkColumn_unittest.cpp
  cubic-server/world_storage/tests/LevelData_unittest.cpp
  cubic-server/world_storage/tests/Level_unittest.cpp
Labels: enhancement

#76 Fix NBT destructors
  cubic-server/nbt.hpp
Labels: bug

#80 Add warn message when compute time outrun max ms per tick
  cubic-server/WorldGroup.cpp
Labels: enhancement

#79 improve cmake debug
  CMakeLists.txt
Labels: enhancement

#56 Player Connection
  cubic-server/Chat.cpp
  cubic-server/Client.cpp
  cubic-server/Client.hpp
  cubic-server/Player.cpp
  cubic-server/Player.hpp
  cubic-server/nbt.hpp
  cubic-server/protocol/ClientPackets.cpp
  cubic-server/protocol/ClientPackets.hpp
  cubic-server/protocol/ServerPackets.cpp
  cubic-server/protocol/ServerPackets.hpp
  cubic-server/protocol/serialization/addPrimaryType.hpp
  cubic-server/protocol/serialization/popPrimaryType.hpp
  cubic-server/types.hpp
  cubic-server/world_storage/ChunkColumn.cpp
  cubic-server/world_storage/ChunkColumn.hpp
Labels: enhancement

#78 world basic generation 2
  cubic-server/Dimension.cpp
  cubic-server/Dimension.hpp
  cubic-server/default/Overworld.cpp
  cubic-server/default/Overworld.hpp
  cubic-server/world_storage/ChunkColumn.cpp
  cubic-server/world_storage/ChunkColumn.hpp
Labels: enhancement

#88 Make the server not commit sepuku every tick
  cubic-server/Dimension.hpp
  cubic-server/default/DefaultWorld.cpp
Labels: enhancement

#91 Ingame branding and Crash prevention
  cubic-server/Client.cpp
  cubic-server/Player.cpp
  cubic-server/protocol/ClientPackets.cpp
  cubic-server/protocol/ClientPackets.hpp
  cubic-server/protocol/ServerPackets.cpp
Labels: bug

#93 Nbt serialization
  cubic-server/CMakeLists.txt
  cubic-server/World.cpp
  cubic-server/nbt.cpp
  cubic-server/nbt.hpp
Labels: enhancement

#94 Some stupid swing arm...
  cubic-server/Entity.cpp
  cubic-server/Player.cpp
  cubic-server/Player.hpp
  cubic-server/protocol/ClientPackets.cpp
  cubic-server/protocol/ClientPackets.hpp
Labels: enhancement

#89 Stop command
  cubic-server/CMakeLists.txt
  cubic-server/Client.cpp
  cubic-server/CommandLine.cpp
  cubic-server/CommandLine.hpp
  cubic-server/Server.cpp
  cubic-server/Server.hpp
  cubic-server/allCommands.hpp
  cubic-server/command_parser/commands/CMakeLists.txt
  cubic-server/command_parser/commands/Stop.cpp
  cubic-server/command_parser/commands/Stop.hpp
  cubic-server/main.cpp
Labels: enhancement

#97 Fix primary type add and pop
  cubic-server/protocol/serialization/addPrimaryType.hpp
  cubic-server/protocol/serialization/popPrimaryType.hpp
Labels: bug

#90 Add update entity position and or rotation packets
  cubic-server/Client.cpp
  cubic-server/Dimension.cpp
  cubic-server/Entity.cpp
  cubic-server/Entity.hpp
  cubic-server/Player.cpp
  cubic-server/Player.hpp
  cubic-server/World.cpp
  cubic-server/math/Vector2.hpp
  cubic-server/math/Vector3.hpp
  cubic-server/protocol/ClientPackets.cpp
  cubic-server/protocol/ClientPackets.hpp
  cubic-server/protocol/Structures.hpp
  cubic-server/protocol/serialization/addPrimaryType.hpp
Labels: enhancement

#74 Add whitelist handling
  configuration/config.yml
  cubic-server/CMakeLists.txt
  cubic-server/Client.cpp
  cubic-server/Server.cpp
  cubic-server/Server.hpp
  cubic-server/configuration/ConfigHandler.cpp
  cubic-server/configuration/ConfigHandler.hpp
  cubic-server/types.hpp
  cubic-server/whitelist/CMakeLists.txt
  cubic-server/whitelist/Whitelist.cpp
  cubic-server/whitelist/Whitelist.hpp
Labels: enhancement

#82 Update interface
  cubic-server/interface/LogsInterface.cpp
  cubic-server/interface/LogsInterface.hpp
  cubic-server/logging/Logger.cpp
  cubic-server/logging/Logger.hpp
Labels: enhancement

#103 Fix binary name in publish workflow
  .github/workflows/publish.yml
Labels: bug

#104 fix all workflows
  .github/workflows/auto_build.yml
  .github/workflows/auto_tests.yml
  .github/workflows/publish.yml
  .github/workflows/requested_build.yml
  .github/workflows/requested_tests.yml
Labels: bug, enhancement
