Repository CubicMC/cubic-server, pull requests merged in 2023-08, with the labels that each got.

#192 Stop the server from playing a bat takeoff sound every 20 seconds
  cubic-server/SoundSystem.cpp
Labels: enhancement

#188 Spruce tree
  cubic-server/generation/features/tree/CMakeLists.txt
  cubic-server/generation/features/tree/birch.cpp
  cubic-server/generation/features/tree/jungle.cpp
  cubic-server/generation/features/tree/oak.cpp
  cubic-server/generation/features/tree/pine.cpp
  cubic-server/generation/features/tree/pine.hpp
  cubic-server/generation/features/tree/spruce.cpp
  cubic-server/generation/features/tree/spruce.hpp
  cubic-server/generation/features/tree/tree.cpp
  cubic-server/generation/features/tree/tree.hpp
  cubic-server/protocol/container/Container.cpp
  cubic-server/protocol/container/Container.hpp
  cubic-server/protocol/container/Inventory.cpp
  cubic-server/protocol/container/Inventory.hpp
Labels: feature

#195 Add bootstrap script + Remove plugin-interface dep
  CMakeLists.txt
  bootstrap.sh
  cubic-server/CMakeLists.txt
  cubic-server/PluginInterface.cpp
  cubic-server/PluginInterface.hpp
  cubic-server/PluginManager.cpp
Labels: enhancement

#198 Add dependencies to the Building section of the README
  README.md
Labels: documentation

#201 Fix bootstrap libc impl check
  bootstrap.sh
Labels: bug, beta
