Repository CubicMC/cubic-server, pull requests merged in 2023-06, with the labels that each got.

#154 Scoreboard system
  cubic-server/CMakeLists.txt
  cubic-server/Entity.cpp
  cubic-server/Player.cpp
  cubic-server/Player.hpp
  cubic-server/Server.cpp
  cubic-server/Server.hpp
  cubic-server/WorldGroup.cpp
  cubic-server/WorldGroup.hpp
  cubic-server/allCommands.hpp
  cubic-server/chat/Message.cpp
  cubic-server/command_parser/commands/CMakeLists.txt
  cubic-server/command_parser/commands/Scoreboard.cpp
  cubic-server/command_parser/commands/Scoreboard.hpp
  cubic-server/protocol/ClientPackets.cpp
  cubic-server/protocol/ClientPackets.hpp
  cubic-server/scoreboard/CMakeLists.txt
  cubic-server/scoreboard/Objectives.cpp
  cubic-server/scoreboard/Objectives.hpp
  cubic-server/scoreboard/Scoreboard.cpp
  cubic-server/scoreboard/Scoreboard.hpp
  cubic-server/scoreboard/ScoreboardSystem.cpp
  cubic-server/scoreboard/ScoreboardSystem.hpp
  cubic-server/scoreboard/Teams.cpp
  cubic-server/scoreboard/Teams.hpp
Labels: feature

#172 Fix default player attributes being always set for creative mode
  CMakeLists.txt
  Jenkinsfile
  cubic-server/Client.cpp
  cubic-server/Client.hpp
  cubic-server/Player.cpp
  cubic-server/PlayerAttributes.hpp
  cubic-server/command_parser/commands/Gamemode.cpp
  cubic-server/configuration/Value.cpp
  cubic-server/logging/Registry.cpp
  cubic-server/loot_tables/CMakeLists.txt
  cubic-server/main.cpp
  cubic-server/protocol/ClientPackets.hpp
  cubic-server/protocol/ServerPackets.hpp
  cxx_flag_overrides.cmake
Labels: bug, beta

#169 Fix test in Release mode and control what boost download/compile
  CMakeLists.txt
  boost.cmake
Labels: bug, enhancement
