Repository CubicMC/cubic-server, pull requests merged in 2024-01, with the labels that each got.

#262 Kubik Server
  .dockerignore
  CMakeLists.txt
  Dockerfile
  README.md
  docker-compose.yaml
Labels: enhancement

#240 Display item in hand
  cubic-server/Player.cpp
  cubic-server/Player.hpp
  cubic-server/protocol/ClientPackets.cpp
  cubic-server/protocol/ClientPackets.hpp
  cubic-server/protocol/container/Inventory.cpp
  cubic-server/scoreboard/Scoreboard.cpp
  cubic-server/scoreboard/Teams.cpp
Labels: feature

#268 Armor damage reduction
  cubic-server/Player.cpp
  cubic-server/PluginInterface.hpp
  cubic-server/Server.cpp
  cubic-server/allCommands.hpp
  cubic-server/command_parser/commands/Armor.cpp
  cubic-server/command_parser/commands/Armor.hpp
  cubic-server/command_parser/commands/CMakeLists.txt
  cubic-server/entities/ArmorStats.hpp
  cubic-server/entities/CMakeLists.txt
  cubic-server/entities/LivingEntity.cpp
  cubic-server/entities/LivingEntity.hpp
  cubic-server/events/Events.hpp
  cubic-server/protocol/container/Inventory.cpp
Labels: feature

#265 Arrow (Bow) handling
  .gitignore
  Jenkinsfile
  cubic-server/Dimension.cpp
  cubic-server/Player.cpp
  cubic-server/Player.hpp
  cubic-server/entities/Arrow.cpp
  cubic-server/entities/Arrow.hpp
  cubic-server/entities/CMakeLists.txt
  cubic-server/entities/Entity.cpp
  cubic-server/entities/Entity.hpp
  cubic-server/items/UsableItem.hpp
  cubic-server/items/usable-items/Bow.cpp
  cubic-server/items/usable-items/Bow.hpp
  cubic-server/items/usable-items/CMakeLists.txt
  cubic-server/items/usable-items/FlintAndSteel.cpp
  cubic-server/items/usable-items/FlintAndSteel.hpp
  cubic-server/items/usable-items/Hoe.cpp
  cubic-server/items/usable-items/Hoe.hpp
  cubic-server/protocol/Structures.cpp
  cubic-server/protocol/Structures.hpp
Labels: enhancement

#256 World save to disk
  cubic-server/CMakeLists.txt
  cubic-server/Server.cpp
  cubic-server/Server.hpp
  cubic-server/command_parser/commands/CMakeLists.txt
  cubic-server/command_parser/commands/SaveRegion.cpp
  cubic-server/command_parser/commands/SaveRegion.hpp
  cubic-server/nnbt.hpp
  cubic-server/protocol/serialization/addPrimaryType.hpp
  cubic-server/protocol_id_converter/blockIdConverter.cpp
  cubic-server/protocol_id_converter/blockIdConverter.hpp
  cubic-server/types.cpp
  cubic-server/types.hpp
  cubic-server/world_storage/ChunkColumn.cpp
  cubic-server/world_storage/ChunkColumn.hpp
  cubic-server/world_storage/Persistence.cpp
  cubic-server/world_storage/Persistence.hpp
Labels: enhancement

#272 Crafting table checks for recipes
  cubic-server/Player.cpp
  cubic-server/protocol/container/CraftingTable.cpp
  cubic-server/protocol/container/CraftingTable.hpp
  cubic-server/protocol/container/Inventory.cpp
  cubic-server/recipes/Blasting.cpp
  cubic-server/recipes/Blasting.hpp
  cubic-server/recipes/CampfireCooking.cpp
  cubic-server/recipes/CampfireCooking.hpp
  cubic-server/recipes/CraftingShaped.cpp
  cubic-server/recipes/CraftingShaped.hpp
  cubic-server/recipes/CraftingShapeless.cpp
  cubic-server/recipes/CraftingShapeless.hpp
  cubic-server/recipes/Recipes.cpp
  cubic-server/recipes/Recipes.hpp
  cubic-server/recipes/Smelting.cpp
  cubic-server/recipes/Smelting.hpp
  cubic-server/recipes/Smithing.cpp
  cubic-server/recipes/Smithing.hpp
  cubic-server/recipes/Smoking.cpp
  cubic-server/recipes/Smoking.hpp
  cubic-server/recipes/SpecialArmorDye.cpp
  cubic-server/recipes/SpecialArmorDye.hpp
  cubic-server/recipes/SpecialBannerDuplicate.cpp
  cubic-server/recipes/SpecialBannerDuplicate.hpp
  cubic-server/recipes/SpecialBookCloning.cpp
  cubic-server/recipes/SpecialBookCloning.hpp
  cubic-server/recipes/SpecialFireworkRocket.cpp
  cubic-server/recipes/SpecialFireworkRocket.hpp
  cubic-server/recipes/SpecialFireworkStar.cpp
  cubic-server/recipes/SpecialFireworkStar.hpp
  cubic-server/recipes/SpecialFireworkStarFade.cpp
  cubic-server/recipes/SpecialFireworkStarFade.hpp
  cubic-server/recipes/SpecialMapCloning.cpp
  cubic-server/recipes/SpecialMapCloning.hpp
  cubic-server/recipes/SpecialMapExtending.cpp
  cubic-server/recipes/SpecialMapExtending.hpp
  cubic-server/recipes/SpecialRepairItem.cpp
  cubic-server/recipes/SpecialRepairItem.hpp
  cubic-server/recipes/SpecialShieldDecoration.cpp
  cubic-server/recipes/SpecialShieldDecoration.hpp
  cubic-server/recipes/SpecialShulkerboxColoring.cpp
  cubic-server/recipes/SpecialShulkerboxColoring.hpp
  cubic-server/recipes/SpecialSuspiciousStew.cpp
  cubic-server/recipes/SpecialSuspiciousStew.hpp
  cubic-server/recipes/SpecialTippedArrow.cpp
  cubic-server/recipes/SpecialTippedArrow.hpp
  cubic-server/recipes/StoneCutting.cpp
  cubic-server/recipes/StoneCutting.hpp
Labels: enhancement

#270 Farmland hydratation and random tick speed mechanics
  .gitignore
  cubic-server/Dimension.cpp
  cubic-server/ai/wandering.cpp
  cubic-server/generation/features/surface/Vegetation.cpp
  cubic-server/generation/features/surface/forestRock.cpp
  cubic-server/generation/features/tree/birch.cpp
  cubic-server/generation/features/tree/jungle.cpp
  cubic-server/generation/features/tree/oak.cpp
  cubic-server/generation/features/tree/pine.cpp
  cubic-server/generation/features/tree/spruce.cpp
  cubic-server/generation/features/underground/OreVein.cpp
  cubic-server/utility/CMakeLists.txt
  cubic-server/utility/RandomTickBlockFunctions.hpp
  cubic-server/utility/random_tick_block_functions/CMakeLists.txt
  cubic-server/utility/random_tick_block_functions/Farmland.cpp
  cubic-server/utility/random_tick_block_functions/Farmland.hpp
  cubic-server/world_storage/ChunkColumn.cpp
  cubic-server/world_storage/ChunkColumn.hpp
  cubic-server/world_storage/Section.cpp
  cubic-server/world_storage/Section.hpp
Labels: feature

#273 Fix remove entities packet
  cubic-server/Dimension.cpp
  cubic-server/protocol/container/CraftingTable.cpp
Labels: bug

#261 Nether Update: Nether Wastes & Nether Portal
  cubic-server/Client.cpp
  cubic-server/Dimension.cpp
  cubic-server/Dimension.hpp
  cubic-server/Player.cpp
  cubic-server/Player.hpp
  cubic-server/SoundSystem.cpp
  cubic-server/default/Overworld.hpp
  cubic-server/default/TheEnd.hpp
  cubic-server/default/TheNether.cpp
  cubic-server/default/TheNether.hpp
  cubic-server/entities/Chicken.cpp
  cubic-server/entities/Entity.cpp
  cubic-server/entities/Entity.hpp
  cubic-server/generation/CMakeLists.txt
  cubic-server/generation/generator.cpp
  cubic-server/generation/nether.cpp
  cubic-server/generation/nether.hpp
  cubic-server/generation/overworld.cpp
  cubic-server/generation/player_constructions/CMakeLists.txt
  cubic-server/generation/player_constructions/NetherPortal.cpp
  cubic-server/generation/player_constructions/NetherPortal.hpp
  cubic-server/items/usable-items/FlintAndSteel.cpp
  cubic-server/items/usable-items/FlintAndSteel.hpp
  cubic-server/protocol/ClientPackets.cpp
  cubic-server/protocol/ClientPackets.hpp
  cubic-server/protocol/serialization/CMakeLists.txt
  cubic-server/registry/Biome.hpp
  cubic-server/registry/Dimension.hpp
  cubic-server/world_storage/ChunkColumn.cpp
  cubic-server/world_storage/Section.hpp
Labels: enhancement, feature
